Hopefully fixed the issues with editing water intervals
ChrisKurz098/Plantz pull request #59
Opened 2022-02-22 01:45 UTC by ChrisKurz098

2022-02-22 01:56 UTC, emdok commented on public/javascript/edit-plant.js
> +      document.location.replace("/");
nice, yes this makes sense. TY!

2022-02-22 01:56 UTC, emdok commented on utils/helpers.js
> +    console.log('Day: ',day,"Weeks: ", week)
Can we remove this console.log?

2022-02-22 01:57 UTC, emdok commented on utils/helpers.js
> +    if (weeksAsDays) week = week*7;
could make this one a ternary as well
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2022-02-22 01:59 UTC, emdok requested changes
Left two very small nits, then this is good to go!

2022-02-23 00:26 UTC, ChrisKurz098 commented
OK. I fixed those issues and then some. There were some security vulnerabilities where any user could send an api request to delete or update any user. Now only if the session user id and requested user id match can a user be updated. Also, now only the admin can delete a user. These two fixes stop someone from being able to update or delete the user admin or update another users info

2022-02-23 01:43 UTC, emdok approved these changes

2022-02-23 01:45 UTC, merged